# Generated by Django 2.2.12 on 2020-06-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phenotype_ontologies', '0002_auto_20180726_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('ontology', 'identifier')},
        ),
    ]
